
services:
  backend:
    build: ./backend
    container_name: cloudops-backend
    ports:
      - "8000:8000"
    networks:
      - cloudops-net

  frontend:
    build: ./frontend
    container_name: cloudops-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - cloudops-net

networks:
  cloudops-net:
    driver: bridge
